### ISSUE TITLE
Model is not registered

### ISSUE THREAD

**Issue by tianyaohu** [MadcowD/ell#1]
### Description

client_example.py works. It uses "gpt-4o", and correctly produce output in terminal and ell.db

All other examples does not work, showing same error, despite having key in C:\\User\\.oaikey
`    raise ValueError(f"No client found for model '{model}'. Ensure the model is registered using 'register_model' in 'config.py' or specify a client directly using the 'client' argument in the decorator or function call.")
ValueError: No client found for model 'gpt-4o'. Ensure the model is registered using 'register_model' in 'config.py' or specify a client directly using the 'client' argument in the decorator or function call.`

Tested with my own script and it is not the openai lib not working.]

### Steps to Reproduce

1. ```- pip install dill
- pip install sqlmodel
- pip install cattrs
- pip install uvicorn
- pip install fastapi```
2.   sl-XXXXXXXXXXXXXXXXXXXXX > C:\\User\\.oaikey

### Expected Behavior

All examples should produce the nice looking output

### Actual Behavior

(ell_lab) D:\dev\ell>D:/anaconda/envs/ell_lab/python.exe d:/dev/ell/examples/joke.py
╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ come_up_with_a_premise_for_a_joke_about(minecraf..) # (notimple...)
╠══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
║ Prompt:
╟──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
│      system: You are an incredibly talented comedian. Come up with a premise for a joke about topic
│
│        user: come up with a premise for a joke about minecraft
Model 'gpt-4o' is not registered. Falling back to OpenAI client from environment variables.
Traceback (most recent call last):
  File "d:\dev\ell\examples\joke.py", line 30, in <module>
    joke("minecraft") # <The joke>
    ^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 190, in wrapper
    else fn(*fn_args, _invocation_origin=invocation_id, **fn_kwargs, )
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 142, in wrapper
    res = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\dev\ell\examples\joke.py", line 24, in joke
    return f"Act out a full joke. Make your script {get_random_length()} words long. Here's the premise: {come_up_with_a_premise_for_a_joke_about(topic)}"
                                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 190, in wrapper
    else fn(*fn_args, _invocation_origin=invocation_id, **fn_kwargs, )
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 148, in wrapper
    tracked_str = _run_lm(**_invocation_kwargs, _invocation_origin=_invocation_origin, _logging_color=color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 77, in _run_lm
    raise ValueError(f"No client found for model '{model}'. Ensure the model is registered using 'register_model' in 'config.py' or specify a client directly using the 'client' argument in the decorator or function call.")
ValueError: No client found for model 'gpt-4o'. Ensure the model is registered using 'register_model' in 'config.py' or specify a client directly using the 'client' argument in the decorator or function call.

###  My own Working Test Script:
```
import os

# Get the home directory path
home_directory = os.path.expanduser("~")

# Construct the full path to the .oaikey file
oaikey_path = os.path.join(home_directory, '.oaikey')

# Read the API key from the file
try:
    with open(oaikey_path, 'r') as file:
        api_key = file.read().strip()
except FileNotFoundError:
    raise Exception(f"API key file not found at {oaikey_path}. Please ensure it exists and the path is correct.")

from openai import OpenAI

client = OpenAI(
  api_key=api_key,
)
# Use the OpenAI API with the correct model name

completion = client.chat.completions.create(
  model="gpt-4o-mini",
  messages=[
    {"role": "system", "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair. Use less than 100 tokens"},
    {"role": "user", "content": "Compose a poem that explains the concept of recursion in programming."}
  ]
)


print(completion.choices[0].message)
```

**Comment by MadcowD** [comment]
You need to set your environment api key variable for the other examples to work:
```
import os
os.environ['OPENAI_API_KEY'] = 'sk-...'
```
Or do it in Windows wherever that is

**Comment by MadcowD** [comment]
- [ ] Make the erorr message more clear so that you actually go and and the API key!

**Comment by tianyaohu** [comment]
Windows needs to have OPENAI_API_KEY env
from openai official doc.
open cmd
setx OPENAI_API_KEY "your-api-key-here"
#verify
echo %OPENAI_API_KEY%

Reopen your IDE VScod  or something else
