### ISSUE TITLE
Anyway to use the model on Azure

### ISSUE THREAD

**Issue by timnew** [MadcowD/ell#158]
It seems ell only supports official OAI API

Wondering anyway to use Azure OAI models? Or I have to create a new provider to do that?

**Comment by MadcowD** [comment]
I think you just need to register your models or use your own client. See https://docs.ell.so/core_concepts/models_and_api_clients.html

**Comment by MadcowD** [comment]
Closed but you can reopen if im stupid

**Comment by dkatsios** [comment]
I couldn't run it with AzureOpenAI 
Here is the code:

```python
import os
from dotenv import load_dotenv

import ell
from openai import AzureOpenAI

load_dotenv()


azure_client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version="2024-03-01-preview",
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
)

ell.config.register_model("azure-gpt", azure_client)


@ell.simple(model="azure-gpt")
def hello(name: str):
    """You are a helpful assistant."""  # System prompt
    return f"Say hello to {name}!"  # User prompt


greeting = hello("Sam Altman")
print(greeting)
```

Breaks with 

`NotFoundError: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}`

**Comment by timnew** [comment]
@dkatsios Seems AZURE_OPENAI_ENDPOINT isn't properly configured. maybe double check it
