### ISSUE TITLE
Request: Access Application on the Network

### ISSUE THREAD

**Issue by transcendr** [MadcowD/ell#166]
I want to be able to access the running application (ell-studio) on the network via the machine's name host (eg, galaxy.local) on MacOS.  Typically in a javascript app you would need to configure the host to be 0.0.0.0 instead of 127.0.0.1. Not sure what the frontend is built on, but I'm sure there are instructions for being able to configure it to start with a custom host.

**Comment by alex-dixon** [comment]
Think this was fixed https://github.com/MadcowD/ell/commit/c7738f6ecaf9c7597a9fba1699f7a3fd60bc8587

**Comment by MadcowD** [comment]
@alex-dixon we should release a new version with this if tis not out yet.
@transcendr can you `pip install --upgrade ell-ai`

**Comment by MadcowD** [comment]
@transcendr oh this isnt out yet
will be out tonight with 0.0.6
