### ISSUE TITLE
Support OpenAI JSON mode

### ISSUE THREAD

**Issue by olafgeibig** [MadcowD/ell#183]
Many API-compatible models, such as those from DeepSeek, support the JSON Mode feature of the OpenAI API. However, if JSON Mode is not activated in the OpenAI client, the responses are returned as JSON enclosed in markdown quotes. This makes it difficult to work with the raw JSON data directly.

To enhance compatibility with these models, I propose adding an option to activate JSON Mode in the OpenAI client, such as by using a parameter like: response_format={'type': 'json_object'}

**Comment by MadcowD** [comment]
Gotcha
