### ISSUE TITLE
opening studio programmatically

### ISSUE THREAD

**Issue by colinricardo** [MadcowD/ell#202]
hi, great library, thank you!

is there a way to programmatically open the studio?

e.g.

```
from ell import studio

studio.open()

```

the `ell-studio` command doesnt work for me (i suspect something to do with using `uv` for installation)

**Comment by colinricardo** [comment]
update, with `uv` we can do: 

`uv run python -m ell.studio --storage ./logdir`

**Comment by MadcowD** [comment]
You can also run 
```
python3 -m ell.studio --storage ./logdir
```
If you want to post your error with the original `ell-studio` please do I'd look forward to it in another issue :)
