### ISSUE TITLE
Can't use local Ollama 

### ISSUE THREAD

**Issue by Madsycode** [MadcowD/ell#224]
Hoe can i manage to get to use my ollama client? It keeps telling me that I have no registered a provide for my client type! How can i do that?
`import ell
import ollama

ell.init(verbose=True)
MODEL = "llama3.1:latest"
OLLAMA_API = "http://127.0.0.1:11434"

ell.config.register_model(MODEL, client)
ell.config.register_provider(...)

client = ollama.Client(host=OLLAMA_API)

@ell.simple(model=MODEL, client=client)
def hello(name : str) -> str:
    """You are a helpful assistant for chatbots.""" 
    return f"Say hello to {name} with a poem." 

response = hello("John Deo")
print(response)`

ERROR:  response = hello("John Deo")
               ^^^^^^^^^^^^^^^^^^^
File "...\.env\Lib\site-packages\ell\lmp\_track.py", line 64, in tracked_func
    return func_to_track(*fn_args, **fn_kwargs, _invocation_origin=invocation_id)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "...\.env\Lib\site-packages\ell\lmp\complex.py", line 64, in model_call
    assert provider is not None, f"No provider found for client {ell_call.client}."
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: No provider found for client <ollama._client.Client object at 0x0000014846AA70E0>.

**Comment by MadcowD** [comment]
```
"""
Ollama example.
"""
import ell

ell.init(verbose=True, store='./logdir')
# Use models automatically registered by asking ollama 
ell.models.ollama.register(base_url="http://localhost:11434/v1")

# in terminal run ollama list to see available models
@ell.simple(model="llama3.1:latest", temperature=0.1)
def write_a_story():
    return "write me a story"
```
or do
```

# Or use the client directly
import openai
client = openai.Client(
    base_url="http://localhost:11434/v1", api_key="ollama"  # required but not used
)
@ell.simple(model="llama3.1:latest", temperature=0.1, max_tokens=100, client=client)
def write_a_story_with_client():
    return "write me a short story"
```
we don't support ollama directly, but you can use the `openai` compatible client like I do above!

**Comment by MadcowD** [comment]
Maybe I'll add thos later into the provider a;sp

**Comment by Madsycode** [comment]
thx!! it worked!
