### ISSUE TITLE
0.0.7 breaks ollama example

### ISSUE THREAD

**Issue by alex-dixon** [MadcowD/ell#228]
% python -m unittest tests.test_greeting

Using model: llama3.1:latest
─────────────────────╢
│   assistant: "Hello, Alice! It's lovely to connect with you
│              today! How's your day going so far? I'm here to listen,
│              help or just chat - whatever makes you feel happy and
│              supported!"
╚════════════════════════════════════════════════════════════════════════╝

======================================================================
ERROR: test_hello_custom (tests.test_greeting.TestGreeting.test_hello_custom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//ell-main/artificial_brain_agent/tests/test_greeting.py", line 25, in test_hello_custom
    greeting = hello_world(name)
               ^^^^^^^^^^^^^^^^^
  File "//venv/lib/python3.12/site-packages/ell/lmp/_track.py", line 122, in tracked_func
    prompt_tokens=usage.get("prompt_tokens", 0)
                  ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

c/o @patchthecode

**Comment by MadcowD** [comment]
fixed
