### ISSUE TITLE
api_params=dict(n=2) may not be supported in Ollama

### ISSUE THREAD

**Issue by thaq1f** [MadcowD/ell#240]
Using identical flows in OpenAI & Ollama yielded an infinite loop, where Ollama passes (H) from 1 LMP to the next 
instead of the generated context. 

![Screenshot 2024-09-25 at 9 28 39 AM](https://github.com/user-attachments/assets/ec92ea1e-a09c-4d3d-91eb-90d7d6cd686c)
![Screenshot 2024-09-25 at 9 28 56 AM](https://github.com/user-attachments/assets/ced82b81-366f-4829-b667-d1d974f9a822)
![Screenshot 2024-09-25 at 9 38 42 AM](https://github.com/user-attachments/assets/b1eea48e-6f6f-4754-a449-705a293650e0)

input from alex to switch: 
openai: api_params=dict(n=2)
to 
ollama: for _ in range(2)

did the trick

**Comment by MadcowD** [comment]
This is a problem with ollama. I've made a PR, who knows if they will accept it!
https://github.com/ollama/ollama/pull/6948 
Currently they don't fail on unsupported parameters leading to your errorr.

For anyone in the future reading this, to get examples like this working, just do as @thaq1f and

input from alex to switch:
openai: api_params=dict(n=2)
to
ollama: for _ in range(2)

did the trick
