### ISSUE TITLE
Support for `format` API param (Ollama JSON mode)

### ISSUE THREAD

**Issue by adstastic** [MadcowD/ell#246]
[Ollama supports JSON mode](https://github.com/ollama/ollama/blob/main/docs/api.md#request-json-mode) using the API param `"format": "json"`

When using this with `ell.complex` or `ell.simple`, I get the error:

```
# .venv/lib/python3.12/site-packages/ell/lmp/_track.py:118
TypeError: Completions.create() got an unexpected keyword argument 'format'
```

Code:
```
MODEL = "llama3.1:latest"

client = OpenAI(
	base_url = "http://localhost:11434/v1",
	api_key = "ollama",
)

ell.config.verbose = True
ell.config.register_model(MODEL, client)

@ell.complex(model=MODEL, client=client, format="json")
def my_function(...)
```

**Comment by MadcowD** [comment]
You need to use the OpenAI API for Ollama:

https://github.com/ollama/ollama/blob/main/docs/openai.md

They do JSON a bit differently: 
https://github.com/ollama/ollama/blob/450acb71a6366ca22eada96ab08c0527a6914c5e/openai/openai.go#L479

Use `response_format=dict({"type": "json_object"})`

**Comment by MadcowD** [comment]
If that doesn't work let me know and I'll patch!
