### ISSUE TITLE
any plan to support use numpy 1? cuz lots of dependency requires numpy<2 in my old project 

### ISSUE THREAD

**Issue by ecpknymt** [MadcowD/ell#265]
![image](https://github.com/user-attachments/assets/f99d4810-be56-4cad-9546-7f3ad6815ffb)
So I would like to try ell, but I cant find a solution to deal with it.

Thanks

**Comment by MadcowD** [comment]
I think we could make it agnostic to numpy version want to look into this?

**Comment by ecpknymt** [comment]
I've pull a request to add support for numpy 1 #267 , and I think it will works

**Comment by MadcowD** [comment]
Thank you!
