### ISSUE TITLE
Incopatibility with sqlmodel and fastapi

### ISSUE THREAD

**Issue by jdgaravito** [MadcowD/ell#284]
Hi, loved ell, but I cant use it on my project unfortunately. 
Here are my dependencies
requires-python = ">=3.10"
dependencies = [
    "asyncpg>=0.29.0",
    "black>=24.8.0",
    "fastapi[standard]>=0.115.0",
    "numpy>=2.1.1",
    "pandas>=2.2.3",
    "psycopg2-binary>=2.9.9",
    "pydantic-settings>=2.5.2",
    "python-dotenv>=1.0.1",
    "scrapy>=2.11.2",
    "sqlmodel>=0.0.22",
]

when i tried to install ell-ai got this:

 No solution found when resolving dependencies for split (python_full_version == '3.10.*'):
  ╰─▶ Because only the following versions of ell-ai are available:
          ell-ai==0.0.1
          ell-ai==0.0.2
          ell-ai==0.0.3
          ell-ai==0.0.4
          ell-ai==0.0.5
          ell-ai==0.0.6
          ell-ai==0.0.7
          ell-ai==0.0.8
          ell-ai==0.0.9
          ell-ai==0.0.10
          ell-ai==0.0.11
          ell-ai==0.0.12
          ell-ai==0.0.13
      and all of:
          ell-ai<=0.0.7
          ell-ai>=0.0.9
      depend on sqlmodel>=0.0.21,<0.0.22, we can conclude that all of:
          ell-ai<0.0.8
          ell-ai>0.0.8
      depend on sqlmodel>=0.0.21,<0.0.22.
      And because ell-ai==0.0.8 was yanked (reason: Regression fixed in 0.0.9), we can conclude that all
      versions of ell-ai depend on sqlmodel>=0.0.21,<0.0.22.
      And because your project depends on ell-ai and sqlmodel>=0.0.22, we can conclude that your project's
      requirements are unsatisfiable.

tried to delete fastapi and used the one that comes with ell on install but even when it work to create a basic api, whein i tried to connect db is broken and not connect no matter what i tried.

ConnectionRefusedError: [Errno 111] Connection refused

uninstalling ell-ai and reinstalled fastapi resolved the connection issues. So I cannot use ell on my project unfortunately.

**Comment by MadcowD** [comment]
kk i need to deal with this sorry

**Comment by alex-dixon** [comment]
@jdgaravito This should be addressed in the next release. 

sqlmodel is still required for tracking at the moment. 

To install with no fast api or sqlmodel (no tracking support). 

pip install ell-ai

To install with no fast-api but for tracking with SQLite (which requires sqlmodel):

pip install ell-ai[sqlite]

**Comment by jdgaravito** [comment]
Thank you, looking forward to test it.
