### ISSUE TITLE
[docs] How to use vllm API in ell?

### ISSUE THREAD

**Issue by medwang1** [MadcowD/ell#318]
I use [vllm](https://github.com/vllm-project/vllm) to deploy LLM. 

Is there any way to use this API in ell?

**Comment by alex-dixon** [comment]
@medwang1 

Yes. There is an example here https://github.com/MadcowD/ell/blob/main/examples/providers/vllm_ex.py

**Comment by medwang1** [comment]
> @medwang1
> 
> Yes. There is an example here https://github.com/MadcowD/ell/blob/main/examples/providers/vllm_ex.py

Awesome! I'll try it, thanks.
