### ISSUE TITLE
Message object does not have tool_call_id which is required when we add tool call message to history

### ISSUE THREAD

**Issue by gurvinder-dhillon** [MadcowD/ell#325]
Basically, if we add tool call to message history, it expects a follow up message that is tool result and it should have the tool_call_id.
Here is the reference - https://platform.openai.com/docs/guides/function-calling
and https://community.openai.com/t/formatting-assistant-messages-after-tool-function-calls-in-gpt-conversations/535360/2

`
BadRequestError: Error code: 400 - {'error': {'message': "Missing parameter 'tool_call_id': messages with role 'tool' must have a 'tool_call_id'.", 'type': 'invalid_request_error', 'param': 'messages.[3].tool_call_id', 'code': None}
`

**Comment by alex-dixon** [comment]
@gurvinder-dhillon Are you using the collect and call tools method like this example https://github.com/MadcowD/ell/blob/main/examples/future/use_tool_once.py or something else?

**Comment by MadcowD** [comment]
Isn't tool call id already on the ToolCall object and ToolResutl object.

**Comment by MadcowD** [comment]
Yeah it's in that content blopck object.
